# Generated by Django 4.0 on 2022-01-02 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(help_text='Enter the new todo', max_length=30)),
                ('completed', models.BooleanField(default=False)),
            ],
        ),
    ]
