# Generated by Django 4.0 on 2022-01-02 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='text',
            field=models.CharField(help_text='Enter the new todo', max_length=30, verbose_name='Your Todo'),
        ),
    ]
