# Generated by Django 4.0 on 2022-01-02 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_todo_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='text',
            field=models.CharField(max_length=30, verbose_name='Your Todo'),
        ),
    ]
